all:
	quicktype -o Sources/DataModel/DataModel.swift --src-lang schema schema.json --swift-5-support  --access-level public --coding-keys  --struct-or-class struct  --protocol equatable --protocol hashable --top-level AllModels
